language: python
python:
- 3.8
- 3.7
install:
- pip install -U tox-travis
script:
- tox
deploy:
  provider: pypi
    distributions: sdist bdist_wheel
  username: "__token__"
  password:
    secure: WGKj4gXRtq2esXd3l5L6t5gCVFuE6qzk8Et2MbE6gFtpW2qAMAYvEMu2IrmXM5ff4Pqm7u8BEoYsMtfdMfhPZNNB+yEk/RX6chx8B7WEAso6THkr+s5SqNE1vrb21YN+f+GhPbbFFAruE2ka8zhkd2ZQb3DbKFmzQAkuFUQW8I/KE7VXYF2Y7yHyrVP9FLu96o1MKJVEki/S8Mkn5DZpes0q8MHlOXK6S/oq5bQpWfcvbiKHiYYZc6HP5duTKEz2dQ0xDxISQ5pxNdjyV1Ys0/wJHAj12fKnnDOM2MbXE7ejHdOIBKG2AUP4z0ByRU6zf1UuBzYI1cTwZZ6PbzUGcALC1hmutTvKkQPhkiu7N5W0TMt2MF+5jXTiW5jQE281URq1b1fEac8yRJ823VvqneBbbJm0YUN+6/m5fplZanNqRGDU1euv5OO/lPokh4miTTEBmQePEG2Ak9Xnzw6b2AaPa39nrNdNmCkCTHnf5t5WFoYVofbzl3ccCw0UKsSPC2AH3GEi4j8lhZhK1+AGSmoV5vVWsm40SyBKvat90Bjm+Ll4xCVk80HZelJdTMdDrL2H/Zqk6QlypEZsUJm8xQIgHbZ+77bbM0km7RJv2UP56QfOdD18Yxw7i/Lc+xm72JL560pzmlwuYWaOcPPo80fPdMG120eh8MTBm8Wy9Ak=
  on:
    tags: true
    repo: pnnl/SOSAT
    python: 3.8
